/* Auto-generated by gulp-icon-font — Jacaré helpers
 * Import alongside SwIcon.jcr and iconfont.css.
 * https://github.com/jacarejs/core
 */
export const iconNames = [
  "fita-de-bookmark",
  "locked",
  "multiple-users-silhouette",
  "partilhar",
  "reiniciar",
  "shield",
  "snow-alt",
  "suporte-1",
  "users"
];

export const iconPrefix = 'swicon';

export function swIconClass(name) {
  return iconPrefix + '-' + name;
}
