/* Auto-generated by gulp-icon-font — React helpers */
import React from "react";

export const iconNames = [
  "fita-de-bookmark",
  "locked",
  "multiple-users-silhouette",
  "partilhar",
  "reiniciar",
  "shield",
  "snow-alt",
  "suporte-1",
  "users"
];

export function SwIcon({ name, className = "", ...props }) {
  const classNames = ["swicon-" + name, className].filter(Boolean).join(" ");
  return <i className={classNames} role="img" aria-hidden={props["aria-label"] ? undefined : true} {...props} />;
}

export function IconFitaDeBookmark(props) {
  return <SwIcon name="fita-de-bookmark" {...props} />;
}

export function IconLocked(props) {
  return <SwIcon name="locked" {...props} />;
}

export function IconMultipleUsersSilhouette(props) {
  return <SwIcon name="multiple-users-silhouette" {...props} />;
}

export function IconPartilhar(props) {
  return <SwIcon name="partilhar" {...props} />;
}

export function IconReiniciar(props) {
  return <SwIcon name="reiniciar" {...props} />;
}

export function IconShield(props) {
  return <SwIcon name="shield" {...props} />;
}

export function IconSnowAlt(props) {
  return <SwIcon name="snow-alt" {...props} />;
}

export function IconSuporte1(props) {
  return <SwIcon name="suporte-1" {...props} />;
}

export function IconUsers(props) {
  return <SwIcon name="users" {...props} />;
}
