<!-- Auto-generated by gulp-icon-font — Vue 3 SFC helper usage via render fn alternatives -->
<script>
export const iconNames = [
  "fita-de-bookmark",
  "locked",
  "multiple-users-silhouette",
  "partilhar",
  "reiniciar",
  "shield",
  "snow-alt",
  "suporte-1",
  "users"
];

export function swIconClass(name) {
  return "swicon-" + name;
}
</script>
